version: '3.8'

services:
  postgres:
    container_name: db
    image: ankane/pgvector:v0.4.4
    restart: always
    ports:
      - "${PORT_DB}:${PORT_DB}"
    env_file:
      - ${ENV_FILE:-.env-dev}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: startupdb

  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - "${PORT_REDIS}:${PORT_REDIS}"
    env_file:
      - ${ENV_FILE:-.env-dev}

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    env_file:
      - ${ENV_FILE:-.env-dev}
    depends_on:
      - postgres
      - redis

  jobs:
    container_name: jobs
    build:
      context: .
      dockerfile: Dockerfile
      target: jobs
    env_file:
      - ${ENV_FILE:-.env-dev}
    depends_on:
      - postgres
      - redis
    ports:
      - "${PORT_JOBS}:${PORT_JOBS}"

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
      target: ui-dev
    ports:
      - "${PORT_UI}:${PORT_UI}"
    env_file:
      - ${ENV_FILE:-.env-dev}
    depends_on:
      - server 