apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: your-container-registry/startupfromscratch-ui:latest # Placeholder
        ports:
        - containerPort: 80 # Assuming UI serves on port 80 (e.g., Nginx or a Node server for SSR)
        envFrom:
          - configMapRef:
              name: ui-config
          - secretRef:
              name: ui-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: / # Or a specific health check endpoint for the UI
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10 