apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 80 # Internal port, matching containerPort in UI deployment
  type: ClusterIP # Or LoadBalancer. ClusterIP is typical if an Ingress controller is used. 