apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: your-container-registry/startupfromscratch-server:latest # Placeholder
        ports:
        - containerPort: 3000 # Assuming server runs on port 3000
        envFrom:
          - configMapRef:
              name: server-config
          - secretRef:
              name: server-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz # Assuming a health check endpoint
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz # Assuming a readiness endpoint
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10 