apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 3000 # Internal port, matching containerPort in deployment
  type: ClusterIP # Or LoadBalancer if direct external access is needed without Ingress 