{{- if .Values.persistence.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vrooli.fullname" . }}-postgres
  labels:
    {{- include "vrooli.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: {{ .Values.replicaCount.postgres }}
  selector:
    matchLabels:
      {{- include "vrooli.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  serviceName: {{ include "vrooli.fullname" . }}-postgres-headless # Important for StatefulSet
  template:
    metadata:
      labels:
        {{- include "vrooli.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          env:
            {{- if and .Values.vso.enabled .Values.vso.secrets.postgres .Values.vso.secrets.postgres.enabled }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vso.secrets.postgres.k8sSecretName }}
                  key: username # Assuming the key in Vault for user is 'username'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vso.secrets.postgres.k8sSecretName }}
                  key: password # Assuming the key in Vault for password is 'password'
            {{- end }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata # Standard location
            # Add other non-sensitive environment variables from values.yaml if needed
            # Example:
            # - name: POSTGRES_DB
            #   value: {{ .Values.postgresql.auth.database | quote }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                {{- if and .Values.vso.enabled .Values.vso.secrets.postgres .Values.vso.secrets.postgres.enabled }}
                - -U
                - $(POSTGRES_USER)
                {{- end }}
                - -d
                - postgres # Check against the default 'postgres' db or a specific app db if defined
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                {{- if and .Values.vso.enabled .Values.vso.secrets.postgres .Values.vso.secrets.postgres.enabled }}
                - -U
                - $(POSTGRES_USER)
                {{- end }}
                - -d
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.postgres.size }}
        {{- if .Values.persistence.postgres.storageClass }}
        {{- if (eq "-" .Values.persistence.postgres.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.postgres.storageClass }}"
        {{- end }}
        {{- end }}
{{- end }} 