{{- range $name, $p := .Values.persistence }}
  {{- if and $p (hasKey $p "enabled") $p.enabled }}
{{/* Ensure the service itself is defined and relevant for PVC -- THIS CHECK WAS REMOVED AS IT WAS BUGGY FOR DATABASES */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vrooli.fullname" $ }}-{{ $name }}
  labels:
    {{- include "vrooli.labels" $ | nindent 4 }}
    {{- include "vrooli.componentLabels" (dict "componentName" $name "root" $) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $p.size }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass }}
  {{- end }}
---
  {{- end }}
{{- end }} 