{{- if .Values.persistence.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrooli.fullname" . }}-redis-headless
  labels:
    {{- include "vrooli.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  clusterIP: None # This makes it a headless service
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "vrooli.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }} 