{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vrooli.fullname" . }}-secret
  labels:
    {{- include "vrooli.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ toYaml .Values.secrets | indent 2 }}
{{- end }} 