{{- if and .Values.vso.enabled .Values.vso.secrets -}}
{{- range $secretKeyName, $secretConfig := .Values.vso.secrets -}}
{{- if $secretConfig.enabled -}}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: {{ include "vrooli.fullname" $ }}-{{ $secretConfig.k8sSecretName | default $secretKeyName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vrooli.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ $secretConfig.vaultAuthRef | default .Values.vso.vaultAuthRef | default (printf "%s-vault-auth" (include "vrooli.fullname" $)) }}
  # path is the full path to the secret in Vault, including the KVv2 'data' component if applicable.
  # For KVv2, this is typically 'secret/data/path/to/secret'
  path: {{ $secretConfig.vaultPath | quote }}

  # Optional: Specify how often VSO should resync the secret from Vault
  # resyncPeriod: "1h"

  # Configuration for the destination Kubernetes Secret
  destination:
    name: {{ $secretConfig.k8sSecretName | default $secretKeyName | quote }}
    create: true
    # Type of the Kubernetes Secret (e.g., Opaque, kubernetes.io/tls, kubernetes.io/dockerconfigjson)
    type: {{ $secretConfig.type | default "Opaque" | quote }}

  # If specific templating is needed (e.g., for .dockerconfigjson)
  {{- if $secretConfig.templates }}
  templates:
    {{- toYaml $secretConfig.templates | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end }}

{{- /* Add other VaultSecret definitions here as needed */ -}} 