{{- if and .Values.vso.enabled .Values.vso.secrets -}}
{{- range $secretName, $secretConfig := .Values.vso.secrets -}}
{{- if $secretConfig.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultSecret
metadata:
  name: {{ include "vrooli.fullname" $ }}-{{ $secretName }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vrooli.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ $secretConfig.vaultAuthRef | default (printf "%s-vault-auth" (include "vrooli.fullname" $)) }}
  # Optional: vaultConnectionRef can be specified if not using the default in the namespace

  # Path to the secret in Vault
  path: {{ $secretConfig.vaultPath | quote }}

  # Optional: Specify the type of the Vault K/V Secrets Engine (kv-v1 or kv-v2)
  # If not specified, VSO attempts to detect the version.
  # kvSecretsEngineVersion: "v2"

  # Optional: Specify how often VSO should resync the secret from Vault
  # resyncPeriod: "1h"

  # Configuration for the destination Kubernetes Secret
  destination:
    name: {{ $secretConfig.k8sSecretName | quote }}
    create: true
    # Optional: Type of the Kubernetes Secret (e.g., Opaque, kubernetes.io/tls)
    {{- if eq $secretName "dockerhub" }}
    type: "kubernetes.io/dockerconfigjson"
    {{- else }}
    type: "Opaque"
    {{- end }}
    # Optional: Annotations to add to the K8s Secret
    # annotations:
---
{{- end -}}
{{- end -}}
{{- end }} 