apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/server
  - ../../base/jobs
  - ../../base/ui

# Example: Patch server deployment for production
patchesStrategicMerge:
  - server-replicas-patch.yaml
  - ui-replicas-patch.yaml
  # Add other production specific patches, e.g., resource limits, env vars

# Example: Add a common label to all resources for this overlay
commonLabels:
  environment: production

# Example: Define image tags for production
images:
  - name: your-container-registry/startupfromscratch-server # Match name in base
    newName: your-container-registry/startupfromscratch-server
    newTag: prod-latest # Or a specific version/commit hash
  - name: your-container-registry/startupfromscratch-jobs
    newName: your-container-registry/startupfromscratch-jobs
    newTag: prod-latest
  - name: your-container-registry/startupfromscratch-ui
    newName: your-container-registry/startupfromscratch-ui
    newTag: prod-latest

# Future: Add ConfigMap/Secret generators or references here for production
# configMapGenerator:
# - name: server-config
#   literals:
#     - SOME_API_URL="https://api.example.com"
# secretGenerator:
# - name: server-secret
#   literals:
#     - API_KEY="production-secret-key" 