# values-dev.yaml
# Overrides for the development environment

config:
  env: development

# Image tags override
services:
  ui:
    tag: dev
  server:
    tag: dev
  jobs:
    tag: dev

# Ingress disabled by default in dev
ingress:
  enabled: false 