# Default values for Vrooli chart
# This file contains configuration that can be overridden per environment

# Chart naming overrides
nameOverride: ""
fullnameOverride: ""

# Global values
image:
  registry: "your-registry/your-project" # FIXME: Update placeholder (e.g., docker.io/myusername)
  pullPolicy: IfNotPresent

replicaCount:
  ui: 1
  server: 1
  jobs: 1
  adminer: 1
  postgres: 1
  redis: 1
  nsfwDetector: 1 # Default replica, but will be controlled by an enabled flag

# Service-specific configurations
services:
  ui:
    repository: ui
    tag: dev
    port: 3000
    probes:
      livenessPath: /healthcheck
      readinessPath: /healthcheck
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  server:
    repository: server
    tag: dev
    port: 5329
    probes:
      livenessPath: /healthcheck
      readinessPath: /healthcheck
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
  jobs:
    repository: jobs
    tag: dev
    port: 9230
    probes:
      livenessPath: /healthcheck
      readinessPath: /healthcheck
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  nsfwDetector:
    enabled: false # Disabled by default, enable in values-prod.yaml or per environment
    repository: steelcityamir/safe-content-ai # repository is the image name part here
    tag: "1.1.0"
    port: 8000 # Internal port the container listens on
    probes: # TCP Probe based on docker-compose healthcheck
      livenessPath: ""
      readinessPath: ""
      useTcpSocket: true # Indicates to use TCP socket probe
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    resources:
      requests:
        cpu: 200m       # Base request, adjust as needed
        memory: 512Mi   # Base request, adjust as needed
      limits:
        cpu: 500m       # Base limit, adjust as needed
        memory: 1Gi     # Base limit, adjust as needed
    gpu:
      enabled: false
      # type: "nvidia.com/gpu" # Common GPU resource type
      # count: 1

# Configuration parameters (non-sensitive)
config:
  projectDir: /srv/app
  env: development

# Sensitive values handled as native Kubernetes Secrets
secrets: {}

# Persistence settings for stateful services
persistence:
  postgres:
    enabled: true
    size: 1Gi
    storageClass: ""
  redis:
    enabled: true
    size: 512Mi
    storageClass: ""
  ui:
    enabled: false
  server:
    enabled: false
  jobs:
    enabled: false
  adminer:
    enabled: false

# Ingress configuration
ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: [] 