# values-dev.yaml
# Overrides for the development environment.
# This file is intentionally kept for future dev-specific overrides.
# Currently, all dev defaults are sourced from values.yaml.
# Add any development-specific value overrides below this line.

config:
  env: development

# Image tags override
services:
  ui:
    tag: dev
  server:
    tag: dev
  jobs:
    tag: dev

# Ingress disabled by default in dev
ingress:
  enabled: false

# Enable Vault Secrets Operator for development
vso:
  enabled: true
  # Development-specific VSO overrides can go here if needed
  # For example, if using a different Vault role or address for dev:
  # vaultAddr: "http://dev-vault.example.com:8200"
  # k8sAuthRole: "vrooli-app-dev"
  # secrets:
  #   postgres:
  #     vaultPath: "secret/data/vrooli-dev/postgres"
  #   app:
  #     vaultPath: "secret/data/vrooli-dev/app-config"
  #   dockerhub:
  #     vaultPath: "secret/data/vrooli-dev/dockerhub-creds" 