# values-dev.yaml
# Overrides for the development environment.
# This file is intentionally kept for future dev-specific overrides.
# Currently, all dev defaults are sourced from values.yaml.
# Add any development-specific value overrides below this line.

config:
  env: development

# Image tags override
services:
  ui:
    tag: dev
  server:
    tag: dev
  jobs:
    tag: dev

# Ingress disabled by default in dev
ingress:
  enabled: false 