# values-dev.yaml
# This file contains configuration overrides specifically for the DEVELOPMENT environment,
# aiming for a lighter setup compared to the HA-ready defaults in values.yaml.

# General config (already in values.yaml, but can be reiterated if desired)
# config:
#   env: development

# Reduce replicas for resource-intensive stateful sets in dev
pgoPostgresql:
  instances:
    count: 1 # Single PostgreSQL instance for dev
    storage:
      size: "2Gi" # Smaller storage for dev Postgres
  pgBouncer:
    replicas: 1 # Single pgBouncer for dev
  # Backups can use default PVC for dev (from values.yaml)

spotahomeRedis:
  redis:
    replicas: 1 # Single Redis instance for dev
    storage:
      persistentVolumeClaim:
        spec:
          resources:
            requests:
              storage: "1Gi" # Smaller storage for dev Redis
  sentinel:
    replicas: 1 # Minimal Sentinels for dev (operator might require at least 1)
  # keepAfterDeletion for Redis PVCs can remain false for dev (from values.yaml)

# VSO is enabled by default in values.yaml, which is fine for dev.
# vso:
#   enabled: true

# Adminer is enabled by default in values.yaml, which is fine for dev.
# adminer:
#   enabled: true