name: Master CI/CD

concurrency:
  group: master
  cancel-in-progress: true

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      ignore_lint_errors:
        description: 'Continue workflow even if linting fails'
        required: false
        type: boolean
        default: false
      ignore_test_errors:
        description: 'Continue workflow even if tests fail'
        required: false
        type: boolean
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: 'yarn' # Removed cache to rely on Corepack
      - name: Enable and Prepare Corepack
        run: |
          corepack enable
          corepack prepare --activate
      - name: Yarn install
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
        continue-on-error: ${{ github.event.inputs.ignore_lint_errors == 'true' }}
      - name: Test
        run: yarn test
        continue-on-error: ${{ github.event.inputs.ignore_test_errors == 'true' }}
      - name: Build
        run: yarn build
      - name: Set up SSH key for deployment
        if: env.VPS_SSH_PRIVATE_KEY != '' # Only run if the secret is set
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
        env:
          VPS_SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
      - name: Deploy to Production
        run: bash scripts/deploy.sh prod
        env:
          SSH_KEY_PATH: ~/.ssh/deploy_key
          DEPLOY_USER: ${{ secrets.VPS_DEPLOY_USER }} # Use environment secret
          DEPLOY_HOST: ${{ secrets.VPS_DEPLOY_HOST }} # Use environment secret
          DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }} # Use environment secret 