{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vrooli.fullname" . }}-config
  labels:
    {{- include "vrooli.labels" . | nindent 4 }}
data:
{{ toYaml .Values.config | indent 2 }}
{{- end }} 