{{- range $name, $p := .Values.persistence }}
  {{- if $p.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vrooli.fullname" $ }}-{{ $name }}
  labels:
    {{- include "vrooli.labels" $ | nindent 4 }}
    {{- include "vrooli.componentLabels" (dict "componentName" $name "root" $) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $p.size }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass }}
  {{- end }}
---
  {{- end }}
{{- end }} 